### ISSUE TITLE
theme installation problem from back end 

### ISSUE THREAD

**Issue by amirgee007** [NeoFragCMS/neofrag-theme-dungeon#2]
i have tried many times to upload theme via admin panel but didn't 
![git](https://cloud.githubusercontent.com/assets/16411441/24563427/a87d439e-1667-11e7-86f3-0a42f4fc99d4.JPG)
![capture](https://cloud.githubusercontent.com/assets/16411441/24563435/af543f88-1667-11e7-8420-42a031d71325.JPG)

upload after selection of file its reset the installer button.

after that, i tried to place these files in cpanel neoforg/themes folder i.e attached picture but it also not showing and not giving me selection option

**Comment by michaelbilcot** [comment]
Hello, this is fixed with the Alpha 0.1.6.1 release of the CMS

**Comment by amirgee007** [comment]
thanks bro you are great i see your all comments.

appreciate you
